# PyPI Mirror Tournament
# Format:
# NAME|INDEX_URL

NovinCloud|https://mirror.novin.cloud/artifactory/api/pypi/pypi/simple
ITO|https://archive.ito.gov.ir/mirror2/python/simple
Liara|https://package-mirror.liara.ir/repository/pypi/simple
Ferdowsi|https://mirror.ferdowsi.cloud/artifactory/api/pypi/pip-virtual/simple
Runflare|https://mirror-pypi.runflare.com/simple
PyPI-Official|https://pypi.org/simple
